import '../../../core/app_export.dart';import 'userprofile5_item_model.dart';import 'blockcard_item_model.dart';import 'userprofile6_item_model.dart';/// This class defines the variables used in the [banking_page],
/// and is typically used to hold data that is passed between different parts of the application.
class BankingModel {Rx<List<Userprofile5ItemModel>> userprofile5ItemList = Rx([Userprofile5ItemModel(lineImage:ImageConstant.imgLine.obs,rectangleImage:ImageConstant.imgRectangle.obs,noiseImage:ImageConstant.imgNoise158x285.obs,mastercardImage:ImageConstant.imgMastercard.obs,cardNumberText: "3455 **** **** 3507".obs,cardHolderText: "Sarah Wegan".obs,expiryDateText: "02/30".obs,expiryDateText2: "02/30".obs)]);

Rx<List<BlockcardItemModel>> blockcardItemList = Rx([BlockcardItemModel(imageClass:ImageConstant.imgThumbsUpOnprimary.obs,text: "Block card".obs),BlockcardItemModel(imageClass:ImageConstant.imgUserOnprimary24x24.obs,text: "Change pin".obs),BlockcardItemModel(imageClass:ImageConstant.imgVuesaxLinearCardEdit.obs,text: "Re-issue".obs)]);

Rx<List<Userprofile6ItemModel>> userprofile6ItemList = Rx([Userprofile6ItemModel(userImage:ImageConstant.imgUserAmber300.obs,locationText: "Naperville".obs,dateTimeText: "15-03-2023 08:48 am".obs,amountText: "120,000".obs,statusText: "Completed".obs),Userprofile6ItemModel(userImage:ImageConstant.imgClose.obs,locationText: "Toledo".obs,dateTimeText: "15-03-2023 08:48 am".obs,amountText: "5,000".obs,statusText: "Completed".obs),Userprofile6ItemModel(userImage:ImageConstant.imgClose.obs,locationText: "Pembroke Pines".obs,dateTimeText: "15-03-2023 08:48 am".obs,amountText: "5,000".obs,statusText: "Pending".obs),Userprofile6ItemModel(locationText: "Fairfield".obs,dateTimeText: "15-03-2023 08:48 am".obs,amountText: "5,000".obs,statusText: "Pending".obs)]);

 }
