import 'controller/create_new_password_controller.dart';import 'package:abu_s_application3/core/app_export.dart';import 'package:abu_s_application3/core/utils/validation_functions.dart';import 'package:abu_s_application3/widgets/app_bar/appbar_leading_image.dart';import 'package:abu_s_application3/widgets/app_bar/appbar_subtitle_one.dart';import 'package:abu_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:abu_s_application3/widgets/custom_elevated_button.dart';import 'package:abu_s_application3/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable
class CreateNewPasswordScreen extends GetWidget<CreateNewPasswordController> {CreateNewPasswordScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 20.h, vertical: 15.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("msg_create_a_new_password".tr, style: CustomTextStyles.titleLargeRegular)), SizedBox(height: 6.v), Align(alignment: Alignment.centerLeft, child: Container(width: 307.h, margin: EdgeInsets.only(right: 45.h), child: Text("msg_remember_to_use".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.labelLargeGray40002_2))), SizedBox(height: 37.v), _buildCreateANewPassword(), SizedBox(height: 17.v), _buildConfirmNewPassword(), SizedBox(height: 52.v), CustomElevatedButton(height: 56.v, text: "lbl_complete".tr), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar() { return CustomAppBar(leadingWidth: 40.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftOnprimary, margin: EdgeInsets.only(left: 16.h, top: 16.v, bottom: 16.v), onTap: () {onTapArrowLeft();}), centerTitle: true, title: AppbarSubtitleOne(text: "lbl_new_password".tr)); } 
/// Section Widget
Widget _buildCreateANewPassword() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_new_password2".tr, style: CustomTextStyles.labelLargeSemiBold12), SizedBox(height: 7.v), Obx(() => CustomTextFormField(controller: controller.newpasswordController, hintText: "msg_enter_your_email".tr, hintStyle: CustomTextStyles.labelLargeGray50001, textInputType: TextInputType.emailAddress, prefix: Container(margin: EdgeInsets.fromLTRB(20.h, 16.v, 8.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgLocationAmber700, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: InkWell(onTap: () {controller.isShowPassword.value = !controller.isShowPassword.value;}, child: Container(margin: EdgeInsets.fromLTRB(12.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgEye, height: 20.adaptSize, width: 20.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, obscureText: controller.isShowPassword.value))]); } 
/// Section Widget
Widget _buildConfirmNewPassword() { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_confirm_new_password".tr, style: CustomTextStyles.labelLargeSemiBold12), SizedBox(height: 6.v), Obx(() => CustomTextFormField(controller: controller.newpasswordController1, hintText: "msg_enter_your_email".tr, hintStyle: CustomTextStyles.labelLargeGray50001, textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress, prefix: Container(margin: EdgeInsets.fromLTRB(20.h, 16.v, 8.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgLocationAmber700, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 56.v), suffix: InkWell(onTap: () {controller.isShowPassword1.value = !controller.isShowPassword1.value;}, child: Container(margin: EdgeInsets.fromLTRB(12.h, 18.v, 20.h, 18.v), child: CustomImageView(imagePath: ImageConstant.imgEye, height: 20.adaptSize, width: 20.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 56.v), validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, obscureText: controller.isShowPassword1.value))]); } 

/// Navigates to the previous screen.
onTapArrowLeft() { Get.back(); } 
 }
