import '../tickets_screen/widgets/chipviewframe_item_widget.dart';import 'controller/tickets_controller.dart';import 'models/chipviewframe_item_model.dart';import 'package:abu_s_application3/core/app_export.dart';import 'package:abu_s_application3/widgets/custom_drop_down.dart';import 'package:abu_s_application3/widgets/custom_elevated_button.dart';import 'package:flutter/material.dart';import 'package:table_calendar/table_calendar.dart';class TicketsScreen extends GetWidget<TicketsController> {const TicketsScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [_buildHorrorStack(), SizedBox(height: 21.v), _buildDirectorWritterRow(), SizedBox(height: 22.v), _buildFrameColumn(), SizedBox(height: 20.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 20.h), child: Text("lbl_select_a_cinema".tr, style: CustomTextStyles.labelLargeGray200_1))), SizedBox(height: 10.v), Padding(padding: EdgeInsets.only(left: 20.h, right: 26.h), child: CustomDropDown(icon: Container(margin: EdgeInsets.only(left: 30.h), child: CustomImageView(imagePath: ImageConstant.imgVector, height: 16.adaptSize, width: 16.adaptSize)), hintText: "msg_cinema_xxi_ambarukmo".tr, hintStyle: CustomTextStyles.titleSmallOnPrimarySemiBold, items: controller.ticketsModelObj.value.dropdownItemList!.value, borderDecoration: DropDownStyleHelper.underLineOnPrimary, filled: false, onChanged: (value) {controller.onSelected(value);})), SizedBox(height: 18.v), _buildRegularDRow(), SizedBox(height: 21.v), _buildChipViewFrame(), SizedBox(height: 5.v)])), bottomNavigationBar: _buildPurchaseTickets())); } 
/// Section Widget
Widget _buildHorrorStack() { return SizedBox(height: 240.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgMaskGroup, height: 240.v, width: 393.h, alignment: Alignment.center), Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.only(left: 19.h, top: 13.v, right: 19.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 32.adaptSize, width: 32.adaptSize, onTap: () {onTapImgArrowLeft();}), Padding(padding: EdgeInsets.only(top: 6.v, bottom: 8.v), child: Text("lbl_tickets".tr, style: theme.textTheme.titleSmall)), CustomImageView(imagePath: ImageConstant.imgAntDesignHeartOutline, height: 32.adaptSize, width: 32.adaptSize)]), SizedBox(height: 27.v), Text("lbl_ratu_ilmu_hitam".tr, style: CustomTextStyles.headlineSmallInter25), SizedBox(height: 8.v), Text("msg_4_6_5_from_imdb".tr, style: CustomTextStyles.bodyMediumOnPrimary), SizedBox(height: 15.v), Row(children: [CustomElevatedButton(height: 28.v, width: 93.h, text: "lbl_horror".tr, buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.bodyMediumOnPrimary15_2), CustomElevatedButton(height: 28.v, width: 94.h, text: "lbl_drama".tr, margin: EdgeInsets.only(left: 8.h), buttonStyle: CustomButtonStyles.fillBlueGray, buttonTextStyle: CustomTextStyles.bodyMediumOnPrimary15_2)])])))])); } 
/// Section Widget
Widget _buildDirectorWritterRow() { return Padding(padding: EdgeInsets.symmetric(horizontal: 21.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgImage4, height: 162.v, width: 113.h, radius: BorderRadius.circular(4.h)), Container(width: 63.h, margin: EdgeInsets.only(left: 15.h, top: 23.v, bottom: 20.v), child: Text("msg_director_writte".tr, maxLines: 5, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumOnPrimary15.copyWith(height: 2.13))), Container(width: 152.h, margin: EdgeInsets.only(left: 8.h, top: 23.v, bottom: 10.v), child: Text("msg_kimo_stamboel".tr, maxLines: 4, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumOnPrimary15.copyWith(height: 2.13)))])); } 
/// Section Widget
Widget _buildFrameColumn() { return Container(padding: EdgeInsets.symmetric(horizontal: 20.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_schedule_date".tr, style: CustomTextStyles.labelLargeGray200_1), SizedBox(height: 11.v), Obx(() => SizedBox(height: 48.v, width: 335.h, child: TableCalendar(locale: 'en_US', firstDay: DateTime(DateTime.now().year - 5), lastDay: DateTime(DateTime.now().year + 5), calendarFormat: CalendarFormat.month, rangeSelectionMode: controller.rangeSelectionMode.value, startingDayOfWeek: StartingDayOfWeek.sunday, headerStyle: HeaderStyle(formatButtonVisible: false, titleCentered: true), calendarStyle: CalendarStyle(outsideDaysVisible: false, isTodayHighlighted: true), daysOfWeekStyle: DaysOfWeekStyle(), headerVisible: false, focusedDay: controller.focusedDay.value, rangeStartDay: controller.rangeStart, rangeEndDay: controller.rangeEnd, onDaySelected: (selectedDay, focusedDay) {if (!isSameDay(controller.selectedDay, selectedDay)) {controller.focusedDay.value = focusedDay; controller.selectedDay = selectedDay; controller.rangeSelectionMode.value = RangeSelectionMode.toggledOn;}}, onRangeSelected: (start, end, focusedDay) {controller.focusedDay.value = focusedDay; controller.rangeEnd = end; controller.rangeStart = start; controller.rangeSelectionMode.value = RangeSelectionMode.toggledOn;}, onPageChanged: (focusedDay) {controller.focusedDay.value = focusedDay;})))])); } 
/// Section Widget
Widget _buildRegularDRow() { return Padding(padding: EdgeInsets.only(left: 20.h, right: 30.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("lbl_regular_2d".tr, style: CustomTextStyles.titleSmallOnPrimarySemiBold), Text("lbl_500_40".tr, style: CustomTextStyles.bodyMediumOnPrimary15_1)])); } 
/// Section Widget
Widget _buildChipViewFrame() { return Obx(() => Wrap(runSpacing: 15.v, spacing: 15.h, children: List<Widget>.generate(controller.ticketsModelObj.value.chipviewframeItemList.value.length, (index) {ChipviewframeItemModel model = controller.ticketsModelObj.value.chipviewframeItemList.value[index]; return ChipviewframeItemWidget(model);}))); } 
/// Section Widget
Widget _buildPurchaseTickets() { return CustomElevatedButton(text: "msg_purchase_tickets".tr, margin: EdgeInsets.only(left: 20.h, right: 20.h, bottom: 27.v)); } 

/// Navigates to the previous screen.
onTapImgArrowLeft() { Get.back(); } 
 }
